### ISSUE TITLE
Проблема апгрейда

### ISSUE THREAD

**Issue by krot4u** [coderaiser/article#3]
Проблема с установкой.
Как удалить и почистить от старой версии систему?
Стояла еще 0.9 версия
Пытался накатить 2.2.1

**Comment by coderaiser** [comment]
Какие были ошибки при установке?
Для версии 2.2.1 требуется установленный [git](https://github.com/bower/bower#windows-users) и [bower](http://bower.io/).

P.S.: Старайтесь создавать issue в [соответственном репозитории](https://github.com/coderaiser/cloudcmd/issues) (желательно на английском).

**Comment by krot4u** [comment]
У меня есть npm-debug.log
https://dl.dropboxusercontent.com/u/761866/npm-debug.log

**Comment by coderaiser** [comment]
У вас старая версия node.js:

``` js
node -v v0.10.15
npm -v 1.2.18
```

Советую вам поставить [iojs](https://iojs.org) или [node.js v0.12](http://nodejs.org).
Первый вариант предпочтительнее.

**Comment by krot4u** [comment]
Обновил node до 0.12
Но при установке cloucmd всеравно возникли ошибки.
А когда захожу непосредственно в приложение получаю ошибку на скриншоте.
![20-03-2015 16-36-55](https://cloud.githubusercontent.com/assets/6033525/6752435/8dae904a-cf1f-11e4-98f3-9b9dd4e20e3b.png)

новый лог установки https://dl.dropboxusercontent.com/u/761866/npm-debug.log

**Comment by coderaiser** [comment]
В новом логе те же версии `node.js` и `npm`:

```
21817 error node -v v0.10.15
21818 error npm -v 1.2.18
```

Я смотрю вы пробуете установить `Cloud Commander` из папки с `io.js`

```
cwd /home/krot/download/iojs-v1.6.1-linux-x64
```

Но вы вызываете `node.js`, установленный глобально, попробуйте использовать [nvm](https://github.com/creationix/nvm) для установки `io.js`.

**Comment by krot4u** [comment]
Выполняю

|--> npm install npm -g
npm http GET https://registry.npmjs.org/npm
npm http 200 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-2.7.3.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-2.7.3.tgz
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@2.7.3 /usr/local/lib/node_modules/npm

Далее 
 npm --version
1.2.18
Почему, не могу понять...

**Comment by coderaiser** [comment]
Попробуйте: `which npm`.

**Comment by krot4u** [comment]
/usr/local/bin/npm

**Comment by coderaiser** [comment]
Попробуйте `nvm`. Я о нем писал выше.
Или скачайте [собранный релиз](https://github.com/coderaiser/cloudcmd/releases).

**Comment by krot4u** [comment]
говорят nodejs 0.12 не поддерживается в Ubuntu Saucy

**Comment by coderaiser** [comment]
Вы пробовали через nvm устанавливать?
Или собраный релиз скачать и запустить через имеющийся node.js:

```
node bin/cloudcmd
```

**Comment by krot4u** [comment]
node bin/cloudcmd.js 
module.js:338
    throw err;
          ^
Error: Cannot find module 'rendy'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /root/cloudcmd/bin/cloudcmd.js:11:23
    at Object.<anonymous> (/root/cloudcmd/bin/cloudcmd.js:91:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

Хотя модуль стоит

ls /usr/local/lib/node_modules
total 24 
drwxr-xr-x  6 nobody  4096 Mar 22 14:53 . 
drwxr-xr-x  6 root    4096 Mar 22 13:43 .. 
drwxr-xr-x  7 nobody  4096 Mar 22 14:33 bower 
drwxr-xr-x  3 nobody  4096 Mar 22 14:23 n 
drwxr-xr-x 10 nobody  4096 Mar 20 15:57 npm 
drwxr-xr-x  3 nobody  4096 Mar 22 14:53 rendy

**Comment by coderaiser** [comment]
`Rendy` судя по всему нет в папке `/root/cloudcmd/nodu_modules`.
Он должен быть установлен локально, согласно данным в [package.json](https://github.com/coderaiser/cloudcmd/blob/66a8e345474a44a6e39235b281abc292f420c04a/package.json#L54)
Вы смотрите на глобальную установку.
Попробуйте выполнить в папке`/root/cloudcmd/`:

```
npm install
```

Либо установть Cloud Commander глобально, с помощью:

```
 npm install cloudcmd -g
```

**Comment by krot4u** [comment]
Вот такая проблема постоянно:
Error: EACCES, permission denied '/root/.config/configstore/insight-bower.yml'
Bower я устанавливал
Файла такого небыло.
Ну ок - создал файл вручную, ради эксперимента, но ошибка осталась.

**Comment by coderaiser** [comment]
[Тут](https://github.com/coderaiser/cloudcmd/issues/23), такая же ошибка, и в репозитории [bower](https://github.com/bower/bower/issues/1607).
Решения два:
1. Установить nvm и выполнить:
   `nvm install iojs && npm i bower -g && npm i cloudcmd -g`
2. Сделать [chown](https://ru.wikipedia.org/wiki/Chown) для директории '/root/.config/configstore/`.

Вы под рутом все время сидите?

**Comment by coderaiser** [comment]
@krot4u у вас получилось запустить Cloud Commander?

**Comment by krot4u** [comment]
Да, но только собранный билд.
node bin/cloudcmd.js
Никак не хочет bower вот с этим разобраться /root/.config/configstore/
Владелец и так root

**Comment by krot4u** [comment]
Кроме того, если запустить собранный билд, то не могу сменить пользователя, если прописать в json/config.json - то не принимает его.

**Comment by coderaiser** [comment]
Что если из папки, в которой находится `cloudcmd` выполнить:

``` sh
npm i bower
node node_modules/.bin/bower install 
```

И то же самое для `dword` и `edward`:

``` sh
cd node_modules/dword && node ../.bin/bower install
cd ../edward && node ../.bin/bower install 
```

**Comment by coderaiser** [comment]
> Кроме того, если запустить собранный билд, то не могу сменить пользователя, если прописать в json/config.json - то не принимает его.

Попробуйте изменить через  конфиг (`F10`) либо любым редактором открыть файл `~/.cloudcmd.json` (но в этом случае вам придется самостоятельно генерировать [хеш пароля](https://github.com/coderaiser/cloudcmd/blob/7fe855edfe2e733f2bbb8c78fec99fa265a6a17a/lib/server/auth.js#L39)).

**Comment by krot4u** [comment]
После этой комманды `node node_modules/.bin/bower install`
мне сказали, что под рутом нельзя. Но если хотите укажите `--allow-root`
Я так и сделал - выполнилось успешно.
Но при выполнении `npm i cloudcmd -g` я опять получил 
Error: EACCES, permission denied '/root/.config/configstore/insight-bower.yml'

**Comment by krot4u** [comment]
По другому как через редактирование cloudcmd.json у меня уже не получится, потому что залогиниться через вэб я не могу.
hash сгенерил, но все равно не работает.

**Comment by coderaiser** [comment]
В [этом issue](https://github.com/coderaiser/cloudcmd/issues/23) все получилось c помощью `nvm`.
По-поводу установки через:

```
npm i cloudcmd -g
```

Без `nvm` вам нужно будет устанавливать с помощью `sudo`, либо поменять права на запись в каталог `/usr/local`:

```
sudo chown -R $USER /usr/local
```

> потому что залогиниться через вэб я не могу.

Попробуйте поставить логин и пароль, что [были по-умолчанию](https://github.com/coderaiser/cloudcmd/blob/797b2263458a08909e69b22967a78e90735907f7/json/config.json#L3L4).

**Comment by krot4u** [comment]
поставил пароль по умолчанию - но что вводить когда требует браузер ?

**Comment by coderaiser** [comment]
Согласно информации на сайте [cloudcmd.io](http://cloudcmd.io) (раздел Config):

```
login    : root
password : toor
```

**Comment by krot4u** [comment]
Не логинится
`{
    "auth": false,
    "username": "root",
    "password": "2b64f2e3f9fee1942af9ff60d40aa5a719db33b8ba8dd4864bb4f11e25ca2bee00907de32a59429602336cac832c8f2eeff5177cc14c864dd116c8bf6ca5d9a9",
    "editor": "edward",
    "diff": true,
    "zip" : true,
    "notifications": false,
    "localStorage": true,
    "buffer": true,
    "dirStorage": false,
    "minify": true,
    "online": true,
    "cache": true,
    "showKeysPanel": true,
    "port": 8000,
    "ip": null
}`

**Comment by coderaiser** [comment]
Нужно перезапустить `Cloud Commander`.

**Comment by krot4u** [comment]
Ну конечно же рестартовал...

**Comment by coderaiser** [comment]
Если в файле `~/.cloudcmd.json` параметр `auth` стоит `false` -  окна авторизации не должно появляться в принципе.

У вас `auth` стоит `false` и в `~/.cloudcmd.json`, и в `cloudcmd/json/config.json`?

**Comment by krot4u** [comment]
Аа.. вот теперь увидел что есть ~/.cloudcmd.json, который почему-то используется при запуске cloudcmd/cloudcmd.js (в нём поправил - заработало)
Почему не используется cloudcmd/json/config.json ?

**Comment by coderaiser** [comment]
Потому, что устанавливается `Cloud Commander` обычно глобально и рутом (если не использовать `nvm`).
А запускаться он может всеми пользователями в системе.
Каждый пользователь может под себя настроить конфиг и он сохранится в `~/.cloudcmd.json`.
А в `json/config.json` хранятся настройки по-умолчанию.

Так же, при обновлении Командера конфигурация не будет потеряна, поскольку она лежит в `home`-каталоге, где и все остальные конфигурационные файлы (других программ).

Это все описано в секции Config на [сайте](http://cloudcmd.io).

**Comment by krot4u** [comment]
Спасибо, за помощь!
Вот далее настраиваю - не хочет параметр ip принимать:
вот так прописал:
`"port": 8000,
    "ip": 192.168.111.2
}
`
Ругается:
cloudcmd-v2.2.1/json/config.json: Unexpected token .
url: http://localhost:undefined

**Comment by coderaiser** [comment]
Не валидный `json`. Нужно в кавычки `ip` прописать:

``` js
"ip": "192.168.111.2"
```

Вам спасибо, добавил [несколько опций](https://github.com/coderaiser/cloudcmd/blob/d1f967b85131d75b18e726d8b0d49055f2765438/json/bin.json), которые, надеюсь, смогут вам упросить жизнь в будующем :).

**Comment by krot4u** [comment]
Всё отлично заработало! Спасибо!
Закрывать тикет?
